AssoSite:
    pattern:  /
    defaults: { _controller: winzouBookBundle:Book:index }

winzou_book_new:
    pattern:  /new
    defaults: { _controller: winzouBookBundle:Book:new }

winzou_book_show:
    pattern:  /show/{id}
    defaults: { _controller: winzouBookBundle:Book:show }

winzou_book_newAccount:
    pattern:  /newAccount
    defaults: { _controller: winzouBookBundle:Book:newAccount }

winzou_book_showAccount:
    pattern:  /showAccount/{id}
    defaults: { _controller: winzouBookBundle:Book:showAccount }