parameters:
    winzou_book.entry.manager.class: winzou\BookBundle\Manager\EntryManager
    winzou_book.entry.entity.class:  Asso\BookBundle\Entity\Entry
    
    winzou_book.account.manager.class: winzou\BookBundle\Manager\AccountManager
    winzou_book.account.entity.class:  Asso\BookBundle\Entity\Account

services:
    winzou_book.entry_manager:
        class:     %winzou_book.entry.manager.class%
        arguments: [@doctrine.orm.entity_manager, %winzou_book.entry.entity.class%]
    
    winzou_book.account_manager:
        class:     %winzou_book.account.manager.class%
        arguments: [@doctrine.orm.entity_manager, %winzou_book.account.entity.class%]