parameters:
    winzou_book.entry.manager.class: winzou\BookBundle\Manager\EntryManager
    
    winzou_book.account.manager.class: winzou\BookBundle\Manager\AccountManager

services:
    winzou_book.entry_manager:
        class:     %winzou_book.entry.manager.class%
        arguments: [@doctrine.orm.entity_manager, %winzou_book.entry.entity.class%]
    
    winzou_book.account_manager:
        class:     %winzou_book.account.manager.class%
        arguments: [@doctrine.orm.entity_manager, %winzou_book.account.entity.class%]

    winzou_book.service:
        class:     winzou\BookBundle\BookService
        arguments: [@winzou_book.entry_manager, @winzou_book.account_manager]